"""Reference motion clips generated by the planner with random commands (no motion capture, no hand animation)."""
from __future__ import annotations
import math
import numpy as np
from planner import Walker, Cmd, wrap
from terrain import Terrain

def random_commands(rng, T, speeds=(0.0, 0.5, 0.9, 1.3, 1.8, 2.6, 3.6), turn=True):
    """Piecewise-constant speed and heading targets."""
    segs = []; t = 0.0; head = 0.0
    while t < T:
        d = rng.uniform(1.2, 3.0)
        v = float(rng.choice(speeds, p=None));
        if turn and rng.random() < 0.6: head = wrap(head + rng.uniform(-1.4, 1.4))
        segs.append((t, v, head)); t += d
    def fn(tt, w):
        cur = segs[0]
        for s in segs:
            if tt >= s[0]: cur = s
        v, h = cur[1], cur[2]
        if v < 0.05: return Cmd(heading=h)
        return Cmd(v=np.array([math.cos(h), math.sin(h)]) * v, heading=h)
    return fn, segs

def make_clip(creature, seed, T=10.0, terrain=None, speeds=(0.0, 0.5, 0.9, 1.3, 1.8, 2.6, 3.6), cmd_fn=None, dt=1 / 60):
    rng = np.random.default_rng(seed)
    terrain = terrain or Terrain(-60, 60, -60, 60, res=0.08)
    fn = cmd_fn or random_commands(rng, T, speeds)[0]
    w = Walker(creature, terrain, pos=(0, 0), heading=0.0, dt=dt)
    n = int(T / dt); every = 2
    Q, ROOT, RR, EE, ST, SP = [], [], [], [], [], []
    sk = creature.skel
    ee_idx = [l.chain[-1] for l in creature.legs] + [a.chain[-1] for a in creature.arms]
    for k in range(n):
        snap = w.step(fn(k * dt, w))
        if k % every == 0:
            Q.append(snap["q"].copy()); ROOT.append(snap["root"].copy()); RR.append(w.R_p.copy())
            # end effectors: foot ankle-to-sole centre points and hand ends
            ee = []
            for l in creature.legs:
                f = l.chain[-1]; ee.append(w.S[f] + w.R[f] @ (0.5 * (l.heel + l.ball)))
            for a in creature.arms:
                h = a.chain[-1]; ee.append(w.E[h])
            EE.append(np.array(ee))
            ST.append([1.0 if ls.stance else 0.0 for ls in w.legs]); SP.append(snap["speed"])
    return dict(q=np.array(Q), root=np.array(ROOT), R=np.array(RR), ee=np.array(EE), stance=np.array(ST), speed=np.array(SP), hz=30)
